version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    # 環境変数の設定　※paswordは直接表示しないほうがいい
    environment:
      - 'DATABASE_PASSWORD=postgres'
    # tty: teletypewriter
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links:
      - db

  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'